// function to get the list of cnpj categories in https://blog.meifacil.com/quero-ser-mei/atividades-mei-permitidas-tabela-completa/
// document.querySelectorAll("#tableProfissoes tbody tr").forEach((item) => { arrProfissoes.push(item.querySelector("td").innerText) })

export const CnpjCategories = [
  "Abatedor(a) De Aves Com Comercialização do Produto Independente",
  "Acabador(a) De Calçados",
  "Açougueiro(a)",
  "Adestrador(a) De Animais Independente",
  "Adestrador(a) De Cães De Guarda",
  "Agente De Correio Franqueado E Permissionário",
  "Agente De Viagens",
  "Agente Funerário",
  "Agente Matrimonial",
  "Alfaiate",
  "Amolador(a) De Artigos De Cutelaria",
  "Animador(a) De Festas",
  "Antiquário(a)",
  "Apicultor(a) Independente",
  "Apurador(a), Coletor(a) E Fornecedor(a) De Recortes De Matérias Publicadas Em Jornais E Revistas",
  "Armador(a) De Ferragens Na Construção Civil",
  "Artesão(ã) Têxtil",
  "Artesão(ã) De Bijuterias",
  "Artesão(ã) Em Borracha",
  "Artesão(ã) Em Cerâmica",
  "Artesão(ã) Em Cimento",
  "Artesão(ã) Em Cortiça, Bambu E Afins",
  "Artesão(ã) Em Couro",
  "Artesão(ã) Em Gesso",
  "Artesão(ã) Em Louças, Vidro E Cristal",
  "Artesão(ã) Em Madeira",
  "Artesão(ã) Em Mármore, Granito, Ardósia E Outras Pedras",
  "Artesão(ã) Em Metais",
  "Artesão(ã) Em Metais Preciosos",
  "Artesão(ã) Em Outros Materiais",
  "Artesão(ã) Em Papel",
  "Artesão(ã) Em Plástico",
  "Artesão(ã) Em Vidro",
  "Astrólogo(a)",
  "Azulejista",
  "Baleiro(a)",
  "Banhista De Animais Domésticos",
  "Barbeiro Independente",
  "Barqueiro(a)",
  "Barraqueiro(a)",
  "Beneficiador(a) De Castanha",
  "Bike Propagandista",
  "Bikeboy (Ciclista Mensageiro)",
  "Bolacheiro(a)/biscoiteiro(a)",
  "Bombeiro(a) Hidráulico",
  "Boneleiro(a) (Fabricante De Bonés)",
  "Bordadeiro(a)",
  "Borracheiro(a)",
  "Britador",
  "Cabeleireiro(a)",
  "Calafetador(a)",
  "Calheiro(a)",
  "Caminhoneiro (a) De Cargas Não Perigosas, Intermunicipal E Interestadual",
  "Cantor(a)/músico(a) Independente",
  "Capoteiro(a)",
  "Carpinteiro(a)",
  "Carpinteiro(a) Instalador(a)",
  "Carregador (Veículos De Transportes Terrestres)",
  "Carregador De Malas",
  "Carroceiro – Coleta De Entulhos E Resíduos",
  "Carroceiro – Transporte De Carga",
  "Carroceiro – Transporte De Mudança",
  "Cartazista, Pintor De Faixas Publicitárias E De Letras",
  "Cerqueiro(a)",
  "Chapeleiro(a)",
  "Chaveiro(a)",
  "Chocolateiro(a)",
  "Churrasqueiro(a) Ambulante",
  "Churrasqueiro(a) Em Domicílio",
  "Clicherista",
  "Cobrador(a) De Dívidas",
  "Colchoeiro(a)",
  "Coletor De Resíduos Não-perigosos",
  "Colocador(a) De Piercing",
  "Colocador(a) De Revestimentos",
  "Comerciante De Artigos E Alimentos Para Animais De Estimação (Pet Shop) Independente (não inclui a venda de medicamentos)",
  "Comerciante De Artigos De Armarinho",
  "Comerciante De Artigos De Bebê",
  "Comerciante De Artigos De Caça, Pesca E Camping",
  "Comerciante De Artigos De Cama, Mesa E Banho",
  "Comerciante De Artigos De Colchoaria",
  "Comerciante De Artigos De Cutelaria",
  "Comerciante De Artigos De Iluminação",
  "Comerciante De Artigos De Joalheria",
  "Comerciante De Artigos De Óptica",
  "Comerciante De Artigos De Relojoaria",
  "Comerciante De Artigos De Tapeçaria, Cortinas E Persianas",
  "Comerciante De Artigos De Viagem",
  "Comerciante De Artigos Do Vestuário E Acessórios",
  "Comerciante De Artigos Eróticos",
  "Comerciante De Artigos Esportivos",
  "Comerciante De Artigos Fotográficos E Para Filmagem",
  "Comerciante De Artigos Funerários",
  "Comerciante De Artigos Médicos E Ortopédicos",
  "Comerciante De Artigos Para Habitação",
  "Comerciante De Artigos Usados",
  "Comerciante De Bebidas",
  "Comerciante De Bicicletas E Triciclos; Peças E Acessórios",
  "Comerciante De Brinquedos E Artigos Recreativos",
  "Comerciante De Cal, Areia, Pedra Britada, Tijolos E Telhas",
  "Comerciante De Calçados",
  "Comerciante De Carvão E Lenha",
  "Comerciante De Cestas De Café Da Manhã",
  "Comerciante De Cosméticos E Artigos De Perfumaria",
  "Comerciante De Discos, Cds, Dvds E Fitas",
  "Comerciante De Eletrodomésticos E Equipamentos De Áudio E Vídeo",
  "Comerciante De Embalagens",
  "Comerciante De Equipamentos De Telefonia E Comunicação",
  "Comerciante De Equipamentos E Suprimentos De Informática",
  "Comerciante De Equipamentos Para Escritório",
  "Comerciante De Ferragens E Ferramentas",
  "Comerciante De Flores, Plantas E Frutas Artificiais",
  "Comerciante De Inseticidas E Raticidas",
  "Comerciante De Instrumentos Musicais E Acessórios",
  "Comerciante De Laticínios",
  "Comerciante De Lubrificantes",
  "Comerciante De Madeira E Artefatos",
  "Comerciante De Materiais De Construção Em Geral",
  "Comerciante De Materiais Hidráulicos",
  "Comerciante De Material Elétrico",
  "Comerciante De Miudezas E Quinquilharias",
  "Comerciante De Molduras E Quadros",
  "Comerciante De Móveis",
  "Comerciante De Objetos De Arte",
  "Comerciante De Peças E Acessórios Novos Para Veículos Automotores",
  "Comerciante De Peças E Acessórios Para Aparelhos Eletroeletrônicos Para Uso Doméstico",
  "Comerciante De Peças E Acessórios Novos Para Motocicletas E Motonetas",
  "Comerciante De Peças E Acessórios Usados Para Motocicletas E Motonetas",
  "Comerciante De Peças E Acessórios Usados Para Veículos Automotores",
  "Comerciante De Perucas",
  "Comerciante De Plantas, Flores Naturais, Vasos E Adubos",
  "Comerciante De Pneumáticos E Câmaras-de-ar",
  "Comerciante De Produtos De Higiene Pessoal",
  "Comerciante De Produtos De Limpeza",
  "Comerciante De Produtos De Panificação",
  "Comerciante De Produtos De Tabacaria",
  "Comerciante De Produtos Naturais",
  "Comerciante De Produtos Para Festas E Natal",
  "Comerciante De Produtos Para Piscinas",
  "Comerciante De Produtos Religiosos",
  "Comerciante De Redes Para Dormir",
  "Comerciante De Sistema De Segurança Residencial",
  "Comerciante De Suvenires, Bijuterias E Artesanatos",
  "Comerciante De Tecidos",
  "Comerciante De Tintas E Materiais Para Pintura",
  "Comerciante De Toldos E Papel De Parede",
  "Comerciante De Vidros",
  "Compoteiro(A)",
  "Confeccionador(A) De Carimbos",
  "Confeiteiro(A)",
  "Costureiro(A) De Roupas, Exceto Sob Medida",
  "Costureiro(A) De Roupas, Sob Medida",
  "Cozinheiro(A) Que Fornece Refeições Prontas E Embaladas Para Consumo",
  "Criador(A) De Animais Domésticos",
  "Criador(A) De Peixes Ornamentais Em Água Doce",
  "Criador(A) De Peixes Ornamentais Em Água Salgada",
  "Crocheteiro(A)",
  "Cuidador(A) De Animais (Pet Sitter)",
  "Cuidador(A) De Idosos E Enfermos",
  "Cunhador(A) De Moedas E Medalhas",
  "Curtidor De Couro",
  "Customizador(a) De Roupas",
  "Depilador(a)",
  "Diarista",
  "Digitador(a)",
  "Disc Jockey (Dj) Ou Video Jockey (Vj)",
  "Distribuidor(A) De Água Potável Em Caminhão Pipa",
  "Doceiro(A)",
  "Dublador(A)",
  "Editor(A) De Jornais Diários",
  "Editor(A) De Jornais Não Diários",
  "Editor(A) De Lista De Dados E De Outras Informações",
  "Editor(A) De Livros",
  "Editor(A) De Revistas",
  "Editor(A) De Vídeo",
  "Eletricista De Automóveis",
  "Eletricista Em Residências E Estabelecimentos Comerciais",
  "Encadernador(A)/plastificador(A)",
  "Encanador",
  "Engraxate",
  "Entregador De Malotes",
  "Envasador(A) E Empacotador(A)",
  "Estampador(A) De Peças Do Vestuário",
  "Esteticista",
  "Esteticista De Animais Domésticos",
  "Estofador(A)",
  "Fabricante De Açúcar Mascavo",
  "Fabricante De Alimentos Prontos Congelados",
  "Fabricante De Amendoim E Castanha De Caju Torrados E Salgados",
  "Fabricante De Amido E Féculas De Vegetais",
  "Fabricante De Artefatos De Funilaria",
  "Fabricante De Artefatos Estampados De Metal, Sob Encomenda Ou Não",
  "Fabricante De Artefatos Para Pesca E Esporte",
  "Fabricante De Artefatos Têxteis Para Uso Doméstico",
  "Fabricante De Artigos De Cutelaria",
  "Fabricante De Aviamentos Para Costura",
  "Fabricante De Balas, Confeitos E Frutas Cristalizadas",
  "Fabricante De Bolsas/bolseiro",
  "Fabricante De Brinquedos Não Eletrônicos",
  "Fabricante De Calçados De Borracha, Madeira E Tecidos E Fibras",
  "Fabricante De Calçados De Couro",
  "Fabricante De Chá",
  "Fabricante De Cintos/cinteiro",
  "Fabricante De Conservas De Frutas",
  "Fabricante De Conservas De Legumes E Outros Vegetais",
  "Fabricante De Embalagens De Cartolina E Papel-cartão",
  "Fabricante De Embalagens De Madeira",
  "Fabricante De Embalagens De Papel",
  "Fabricante De Especiarias",
  "Fabricante De Esquadrias Metálicas Sob Encomenda Ou Não",
  "Fabricante De Fios De Algodão",
  "Fabricante De Fios De Linho, Rami, Juta, Seda E Lã",
  "Fabricante De Fumo E Derivados Do Fumo",
  "Fabricante De Geléia De Mocotó",
  "Fabricante De Gelo Comum",
  "Fabricante De Guarda-chuvas E Similares",
  "Fabricante De Guardanapos E Copos De Papel",
  "Fabricante De Instrumentos Musicais",
  "Fabricante De Jogos Recreativos",
  "Fabricante De Laticínios",
  "Fabricante De Letreiros, Placas E Painéis Não Luminosos, Sob Encomenda Ou Não",
  "Fabricante De Luminárias E Outros Equipamentos De Iluminação",
  "Fabricante De Malas",
  "Fabricante De Massas Alimentícias",
  "Fabricante De Meias",
  "Fabricante De Mochilas E Carteiras",
  "Fabricante De Painéis E Letreiros Luminosos",
  "Fabricante De Pão De Queijo Congelado",
  "Fabricante De Papel",
  "Fabricante De Partes De Peças Do Vestuário – Facção",
  "Fabricante De Partes De Roupas Íntimas – Facção",
  "Fabricante De Partes De Roupas Profissionais – Facção",
  "Fabricante De Partes Para Calçados",
  "Fabricante De Polpas De Frutas",
  "Fabricante De Produtos De Soja",
  "Fabricante De Produtos De Tecido Não Tecido Para Uso Odonto-médico- Hospitalar",
  "Fabricante De Produtos Derivados De Carne",
  "Fabricante De Produtos Derivados Do Arroz",
  "Fabricante De Rapadura E Melaço",
  "Fabricante De Refrescos, Xaropes E Pós Para Refrescos",
  "Fabricante De Roupas Íntimas",
  "Fabricante De Sucos Concentrados De Frutas, Hortaliças E Legumes",
  "Fabricante De Sucos De Frutas, Hortaliças E Legumes",
  "Fabricante De Velas, Inclusive Decorativas",
  "Farinheiro De Mandioca",
  "Farinheiro De Milho",
  "Ferramenteiro(A)",
  "Ferreiro/forjador",
  "Filmador(A)",
  "Fornecedor(A) De Alimentos Preparados Para Empresas",
  "Fosseiro (Limpador De Fossa)",
  "Fotocopiador(A)",
  "Fotógrafo(A)",
  "Fotógrafo(A) Aéreo",
  "Fotógrafo(A) Submarino",
  "Funileiro / Lanterneiro",
  "Galvanizador(A)",
  "Gesseiro(A)",
  "Gravador(A) De Carimbos",
  "Guardador(A) De Móveis",
  "Guia De Turismo",
  "Guincheiro (Reboque De Veículos)",
  "Humorista E Contador De Histórias",
  "Instalador(A) De Antenas De Tv",
  "Instalador(A) De Equipamentos De Segurança Domiciliar E Empresarial, Sem Prestação De Serviços De Vigilância E Segurança",
  "Instalador(A) De Equipamentos Para Orientação À Navegação Marítima, Fluvial E Lacustre",
  "Instalador(A) De Isolantes Acústicos E De Vibração",
  "Instalador(A) De Isolantes Térmicos",
  "Instalador(A) De Máquinas E Equipamentos Industriais",
  "Instalador(A) De Painéis Publicitários",
  "Instalador(A) De Rede De Computadores",
  "Instalador(A) De Sistema De Prevenção Contra Incêndio",
  "Instalador(A) E Reparador (A) De Acessórios Automotivos",
  "Instalador(A) E Reparador De Cofres, Trancas E Travas De Segurança",
  "Instalador(A) E Reparador(A) De Elevadores, Escadas E Esteiras Rolantes",
  "Instalador(A) E Reparador(A) De Sistemas Centrais De Ar Condicionado, De Ventilação E Refrigeração",
  "Instrutor(A) De Arte E Cultura Em Geral",
  "Instrutor(A) De Artes Cênicas",
  "Instrutor(A) De Cursos Gerenciais",
  "Instrutor(A) De Cursos Preparatórios",
  "Instrutor(A) De Idiomas",
  "Instrutor(A) De Informática",
  "Instrutor(A) De Música",
  "Jardineiro(A)",
  "Jornaleiro(A)",
  "Lapidador(A)",
  "Lavadeiro(A) De Roupas",
  "Lavadeiro(A) De Roupas Profissionais",
  "Lavador(A) De Estofado E Sofá",
  "Lavador(A) E Polidor De Carro",
  "Livreiro(A)",
  "Locador De Andaimes",
  "Locador(A) De Aparelhos De Jogos Eletrônicos",
  "LOCADOR(A) DE BICICLETAS, INDEPENDENTE",
  "Locador(A) De Equipamentos Científicos, Médicos E Hospitalares, Sem Operador",
  "Locador(A) De Equipamentos Recreativos E Esportivos",
  "Locador(A) De Fitas De Vídeo, Dvds E Similares",
  "Locador(A) De Instrumentos Musicais",
  "Locador(A) De Livros, Revistas, Plantas E Flores",
  "Locador(A) De Máquinas E Equipamentos Agrícolas Sem Operador",
  "Locador(A) De Máquinas E Equipamentos Para Construção Sem Operador, Exceto Andaimes",
  "Locador(A) De Máquinas E Equipamentos Para Escritório",
  "LOCADOR(A) DE MATERIAL E EQUIPAMENTO ESPORTIVO, INDEPENDENTE",
  "Locador(A) De Material Médico",
  "LOCADOR(A) DE MOTOCICLETA, SEM CONDUTOR, INDEPENDENTE",
  "Locador(A) De Móveis E Utensílios, Inclusive Para Festas",
  "Locador(a) De Objetos Do Vestuário, Jóias E Acessórios",
  "Locador(a) De Outras Máquinas E Equipamentos Comerciais E Industriais Não Especificados Anteriormente, Sem Operador",
  "Locador(a) De Palcos, Coberturas E Outras Estruturas De Uso Temporário, Exceto Andaimes",
  "LOCADOR(A) DE VÍDEO GAMES, INDEPENDENTE",
  "Locutor(a) De Mensagens Fonadas E Ao Vivo",
  "Mágico(a)",
  "Manicure/pedicure",
  "Maquiador(a)",
  "Marceneiro (a) Sob Encomenda Ou Não",
  "Marmiteiro(a)",
  "Mecânico(a) De Motocicletas E Motonetas",
  "Mecânico(a) De Veículos",
  "Merceeiro(a)/vendeiro(a)",
  "Mergulhador(a) (Escafandrista)",
  "Moendeiro(a)",
  "Montador(a) De Móveis",
  "Montador(a) E Instalador De Sistemas E Equipamentos De Iluminação E Sinalização Em Vias Públicas, Portos E Aeroportos",
  "Motoboy",
  "Motorista (por aplicativo ou não) Independente",
  "Mototaxista",
  "Moveleiro(a)",
  "Moveleiro(a) De Móveis Metálicos",
  "Oleiro(a)",
  "Organizador(a) De Excursões Em Veículo Próprio, Municipal",
  "Ourives",
  "Padeiro(a)",
  "Panfleteiro(a)",
  "Papeleiro(a)",
  "Pastilheiro(a)",
  "Pedreiro",
  "Peixeiro(a)",
  "Pintor(a) De Automóveis",
  "Pintor(a) De Parede",
  "Pipoqueiro(a)",
  "Piscineiro(a)",
  "Pizzaiolo(a) Em Domicílio",
  "Poceiro/Cisterneiro/Cacimbeiro",
  "Prestador(a) De Serviços de Colheita, Sob Contrato de Empreitada, Independente",
  "Prestador(a) De Serviços de Poda, Sob Contrato de Empreitada, Independente",
  "Prestador(a) De Serviços de Preparação de Terrenos, Sob Contrato de Empreitada, Independente",
  "Prestador(a) De Serviços de Roçagem, Destocamento, Lavração, Gradagem e Sulcamento, Sob Contrato de Empreitada, Independente",
  "Prestador(a) De Serviços de Semeadura, Sob Contrato de Empreitada, Independente",
  "Professor(a) Particular",
  "Promotor(a) De Eventos",
  "Promotor(a) De Turismo Local",
  "Promotor(a) De Vendas",
  "Proprietário(a) De Albergue Não Assistencial",
  "Proprietário(a) De Bar E Congêneres com entretenimento",
  "Proprietário(a) De Bar E Congêneres sem entretenimento",
  "Proprietário(a) De Camping",
  "Proprietário(a) De Cantinas",
  "Proprietário(a) De Carro De Som Para Fins Publicitários",
  "Proprietário(a) De Casa De Chá",
  "Proprietário(a) De Casa De Sucos",
  "Proprietário(a) De Casas De Festas E Eventos",
  "Proprietário(a) De Estacionamento De Veículos",
  "Proprietário(a) De Fliperama",
  "Proprietário(a) De Hospedaria",
  "Proprietário(a) De Lanchonete",
  "Proprietário(a) De Pensão",
  "Proprietário(a) De Restaurante",
  "Proprietário(a) De Sala De Acesso À Internet",
  "Proprietário(a) De Salão De Jogos De Sinuca E Bilhar",
  "Queijeiro(a)/ Manteigueiro(a)",
  "Quitandeiro(a)",
  "Quitandeiro(a) Ambulante",
  "Recarregador(a) De Cartuchos Para Equipamentos De Informática",
  "Reciclador(a) De Borracha, Madeira, Papel E Vidro",
  "Reciclador (a) De Materiais Metálicos, Exceto Alumínio",
  "Reciclador (a) De Materiais Plásticos",
  "Reciclador (a) De Sucatas De Alumínio",
  "Redeiro(a)",
  "Relojoeiro(a)",
  "Rendeiro(a)",
  "Reparador (A) De Artigos De Tapeçaria",
  "Reparador(A) De Aparelhos E Equipamentos Para Distribuição E Controle De Energia Elétrica",
  "Reparador(A) De Artigos E Acessórios Do Vestuário",
  "Reparador(A) De Balanças Industriais E Comerciais",
  "Reparador(A) De Baterias E Acumuladores Elétricos, Exceto Para Veículos",
  "Reparador(A) De Bicicleta",
  "Reparador(A) De Brinquedos",
  "Reparador(A) De Cordas, Velames E Lonas",
  "Reparador(A) De Embarcações Para Esporte E Lazer",
  "Reparador(A) De Equipamentos Esportivos",
  "Reparador(A) De Equipamentos Hidráulicos E Pneumáticos, Exceto Válvulas",
  "Reparador(A) De Equipamentos Médico- Hospitalares Não-eletrônicos",
  "Reparador(A) De Extintor De Incêndio",
  "Reparador(A) De Filtros Industriais",
  "Reparador(A) De Geradores, Transformadores E Motores Elétricos",
  "Reparador(A) De Guarda Chuva E Sombrinhas Independente",
  "Reparador(A) De Instrumentos Musicais",
  "Reparador(A) De Máquinas De Escrever, Calcular E De Outros Equipamentos Não-eletrônicos Para Escritório",
  "Reparador(A) De Máquinas E Aparelhos De Refrigeração E Ventilação Para Uso Industrial E Comercial",
  "Reparador(A) De Máquinas E Aparelhos Para A Indústria Gráfica",
  "Reparador(A) De Máquinas E Equipamentos Para A Indústria Da Madeira",
  "Reparador(A) De Máquinas E Equipamentos Para A Indústria Têxtil, Do Vestuário, Do Couro E Calçados",
  "Reparador(A) De Máquinas E Equipamentos Para Agricultura E Pecuária",
  "Reparador(A) De Máquinas E Equipamentos Para As Indústrias De Alimentos, Bebidas E Fumo",
  "Reparador(A) De Máquinas Motrizes Não-elétricas Lanchonetes",
  "Reparador(A) De Máquinas Para Bares e Lanchonetes Independente",
  "Reparador(A) De Máquinas Para Encadernação Equipamentos Para Instalações Térmicas",
  "Reparador(A) De Máquinas, Aparelhos e Equipamentos Para Instalações Térmicas",
  "Reparador(A) De Móveis",
  "Reparador(A) De Panelas (Paneleiro)",
  "Reparador(A) De Tanques, Reservatórios Metálicos E Caldeiras, Exceto Para Veículos",
  "Reparador(A) De Toldos E Persianas",
  "Reparador(A) De Tonéis, Barris E Paletes De Madeira",
  "Reparador(A) De Tratores Agrícolas",
  "Reparador(A) De Veículos De Tração Animal",
  "Restaurador(A) De Instrumentos Musicais Históricos",
  "Restaurador(A) De Jogos Acionados Por Moedas",
  "Restaurador(A) De Livros",
  "Restaurador(A) De Obras De Arte",
  "Retificador(A) De Motores Para Veículos Automotores",
  "Revelador(A) Fotográfico",
  "Salgadeiro(A)",
  "Salineiro/extrator De Sal Marinho",
  "Salsicheiro(A)/linguiceiro(A)",
  "Sapateiro(A)",
  "Seleiro(A)",
  "Serigrafista",
  "Serigrafista Publicitário",
  "Serralheiro(a), Exceto para Esquadrias, Sob Encomenda Ou Não, Independente",
  "Sintequeiro(A)",
  "Soldador(A) / Brasador(A)",
  "Sorveteiro(A)",
  "Sorveteiro(A) Ambulante",
  "Tanoeiro(A)",
  "Tapeceiro(A)",
  "Tatuador(A)",
  "Taxista",
  "Tecelão(ã)",
  "Tecelão(ã) De Algodão",
  "Técnico(A) De Manutenção De Computador",
  "Técnico(A) De Manutenção De Eletrodomésticos",
  "Técnico(A) De Manutenção De Telefonia",
  "Técnico(A) De Sonorização E De Iluminação",
  "Telhador(A)",
  "Tintureiro(A)",
  "Torneiro(A) Mecânico",
  "Tosador(A) De Animais Domésticos",
  "Tosquiador(A)",
  "Transportador(A) Aquaviário Para Passeios Turísticos",
  "Transportador(A) De Mudanças",
  "Transportador(A) Escolar",
  "Transportador(A) Intermunicipal Coletivo De Passageiros Sob Frete Em Região Metropolitana Independente",
  "Transportador(A) Intermunicipal E Interestadual De Travessia Por Navegação Fluvial",
  "Transportador(A) Marítimo De Carga",
  "Transportador(A) Municipal De Cargas Não Perigosas(Carreto)",
  "Transportador(A) Municipal Coletivo De Passageiros Sob Frete Independente",
  "Transportador(A) Municipal De Travessia Por Navegação",
  "Transportador(A) Municipal Hidroviário De Cargas",
  "Tricoteiro(A)",
  "Vassoureiro(A)",
  "Vendedor(A) Ambulante De Produtos Alimentícios",
  "Vendedor(A) De Aves Vivas, Coelhos E Outros Pequenos Animais Para Alimentação",
  "Verdureiro",
  "Vidraceiro De Automóveis",
  "Vidraceiro De Edificações",
  "Vinagreiro",
  "Viveirista Independente",
];
